[build]
builder = "NIXPACKS"
nixpacksVersion = "1.15.0"
buildCommand = "pip install -r requirements.txt && npm install && npm run build"

[deploy]
startCommand = "gunicorn wsgi:app"
healthcheckPath = "/api/contacts/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5 